spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest11
    password: guest
server:
  port: 8081


#  spring:
#    rabbitmq:
#      host: 39.98.167.70
#      port: 30004
#      username: meijiabang
#      password: MooYoo1491625367meijiabang
#      virtual-host: meijiabang
#  server:
#    port: 8081